Auto Mapping Objects/FastFood.Core/ViewModels/Employees/RegisterEmployeeViewModel.cs
namespace FastFood.Core.ViewModels.Employees
{
    public class RegisterEmployeeViewModel
    {
        public int PositionId { get; set; }
    }
}

Auto Mapping Objects/FastFood.Core/ViewModels/ErrorViewModel.cs
namespace FastFood.Core.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Auto Mapping Objects/FastFood.Core/ViewModels/Items/CreateItemInputModel.cs
namespace FastFood.Core.ViewModels.Items
{
    public class CreateItemInputModel
    {
        public string Name { get; set; }

        public decimal Price { get; set; }

        public int CategoryId { get; set; }
    }
}

Auto Mapping Objects/FastFood.Core/ViewModels/Items/CreateItemViewModel.cs
namespace FastFood.Core.ViewModels.Items
{
    public class CreateItemViewModel
    {
        public int CategoryId { get; set; }
    }
}

Auto Mapping Objects/FastFood.Core/ViewModels/Orders/CreateOrderInputModel.cs
namespace FastFood.Core.ViewModels.Orders
{
    public class CreateOrderInputModel
    {
        public string Customer { get; set; }

        public int ItemId { get; set; }

        public int EmployeeId { get; set; }

        public int Quantity { get; set; }
    }
}

Auto Mapping Objects/FastFood.Core/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using FastFood.Web.ViewModels.Categories;
using FastFood.Services.Data;

namespace FastFood.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService categoryService;
        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            await categoryService.CreateASync(model);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> All()
        {
            IEnumerable<CategoryAllViewModel> categories = await categoryService.GetAllAsync();

            return View(categories.ToList());
        }
    }
}

Auto Mapping Objects/FastFood.Core/Controllers/EmployeesController.cs
namespace FastFood.Web.Controllers
{
    using System;
    using AutoMapper;
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels.Employees;

    public class EmployeesController : Controller
    {
        private readonly FastFoodContext _context;
        private readonly IMapper _mapper;

        public EmployeesController(FastFoodContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IActionResult Register()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public IActionResult Register(RegisterEmployeeInputModel model)
        {
            throw new NotImplementedException();
        }

        public IActionResult All()
        {
            throw new NotImplementedException();
        }
    }
}

Auto Mapping Objects/FastFood.Core/Controllers/HomeController.cs
namespace FastFood.Web.Controllers
{
    using System.Diagnostics;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels;

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Auto Mapping Objects/FastFood.Core/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using FastFood.Web.ViewModels.Items;
using FastFood.Services.Data;

namespace FastFood.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly IItemService itemService;
        public ItemsController(IItemService itemService)
        {
            this.itemService = itemService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            IEnumerable<CreateItemViewModel> availableCategories =
               await itemService.GetAllAvailableCategoriesASync();
            return View(availableCategories.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateItemInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            await itemService.CreateAsync(model);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> All()
        {
            IEnumerable<ItemsAllViewModels> items = 
                await itemService.GetAllAsync();

            return View(items.ToList());
        }   
    }
}

Auto Mapping Objects/FastFood.Core/Controllers/OrdersController.cs
namespace FastFood.Web.Controllers
{
    using System;
    using System.Linq;
    using AutoMapper;
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels.Orders;

    public class OrdersController : Controller
    {
        private readonly FastFoodContext _context;
        private readonly IMapper _mapper;

        public OrdersController(FastFoodContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IActionResult Create()
        {
            //var viewOrder = new CreateOrderViewModel
            //{
            //    Items = _context.Items.Select(x => x.Id).ToList(),
            //    Employees = _context.Employees.Select(x => x.Id).ToList(),
            //};

            return View( );
        }

        [HttpPost]
        public IActionResult Create(CreateOrderInputModel model)
        {
            return RedirectToAction("All", "Orders");
        }

        public IActionResult All()
        {
            throw new NotImplementedException();
        }
    }
}

Auto Mapping Objects/FastFood.Core/Controllers/PositionsController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using FastFood.Data;
using FastFood.Models;
using Microsoft.AspNetCore.Mvc;
using FastFood.Web.ViewModels.Positions;
using FastFood.Services.Data;

namespace FastFood.Web.Controllers
{
    public class PositionsController : Controller
    {
        private readonly IPositionsService positionsService;

        public PositionsController(IPositionsService positionService)
        {
            this.positionsService = positionService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePositionInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            await positionsService.CreateAsync(model);

            return RedirectToAction("All", "Positions");
        }

        public async Task<IActionResult> All()
        {
           IEnumerable<PositionsAllViewModel> positions = await positionsService.GetAllAsync();

            return View(positions.ToList());
        }
    }
}

Auto Mapping Objects/FastFood.Core/Views/Categories/All.cshtml
@model IList<FastFood.Web.ViewModels.Categories.CategoryAllViewModel>

@{
    ViewData["Title"] = "All Categories";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr class="hr-2" />
<table class="table">
    <thead>
        <tr class="row justify-content-center">
            <th class="col-md-1">#</th>
            <th class="col-md-2">Category</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Count(); i++)
        {
            <tr class="row justify-content-center">
                <th class="col-md-1">@(i + 1)</th>
                <td class="col-md-2">@Model[i].Name</td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a class="btn btn-primary ms-1" asp-controller="Categories" asp-action="Create">Create</a>
</div>

Auto Mapping Objects/FastFood.Core/Views/Categories/Create.cshtml
@{
    ViewData["Title"] = "Create Category";
}
<h1 class="text-center">Create Category</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Categories" asp-action="Create" method="post">
    <div class="form-group">
        <label for="categoryName">Category Name</label>
        <input type="text" class="form-control" id="categoryName" placeholder="Category Name..." name="categoryName">
    </div>
    <hr class="bg-secondary half-width" />
	<div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary me-1">Create</button>
        <a class="btn btn-primary ms-1" asp-controller="Categories" asp-action="All">View All</a>
    </div>
</form>

Auto Mapping Objects/FastFood.Core/Views/Employees/All.cshtml
@model IList<FastFood.Web.ViewModels.Employees.EmployeesAllViewModel>

@{
    ViewData["Title"] = "All Employees";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr class="hr-2" />
<table class="table">
    <thead>
        <tr class="row justify-content-center">
            <th class="col-md-1">#</th>
            <th class="col-md-2">Name</th>
            <th class="col-md-2">Age</th>
            <th class="col-md-2">Address</th>
            <th class="col-md-2">Position</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Count(); i++)
        {
            <tr class="row justify-content-center">
                <th class="col-md-1">@(i + 1)</th>
                <td class="col-md-2">@Model[i].Name</td>
                <td class="col-md-2">@Model[i].Age</td>
                <td class="col-md-2">@Model[i].Address</td>
                <td class="col-md-2">@Model[i].Position</td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a class="btn btn-primary ms-1" asp-controller="Employees" asp-action="Register">Register</a>
</div>

Auto Mapping Objects/FastFood.Core/Views/Employees/Register.cshtml
@model IList<FastFood.Web.ViewModels.Employees.RegisterEmployeeViewModel>

@{
    ViewData["Title"] = "Register Employee";
}
<h1 class="text-center">Register Employee</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Employees" asp-action="Register" method="post">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" placeholder="Name..." name="name">
    </div>
    <div class="form-group">
        <label for="age">Age</label>
        <input type="number" step="1" min="18" class="form-control" id="age" placeholder="Age..." name="age">
    </div>
    <div class="form-group">
        <label for="position">Position Id</label>
        <select id="position" class="form-control" name="PositionId">
            @foreach (var position in Model)
            {
                <option value="@position.PositionId">@position.PositionId</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="address">Address</label>
        <input type="text" class="form-control" id="address" placeholder="Address..." name="address" />
    </div>
    <hr class="bg-secondary half-width" />
	<div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary me-1">Register</button>
        <a class="btn btn-primary ms-1" asp-controller="Employees" asp-action="All">View All</a>
    </div>
</form>

Auto Mapping Objects/FastFood.Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="p-5 mb-4 bg-light rounded">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to Fast Food App</h1>
    </div>
</div>

Auto Mapping Objects/FastFood.Core/Views/Items/All.cshtml
@model IList<FastFood.Web.ViewModels.Items.ItemsAllViewModels>

@{
    ViewData["Title"] = "All Items";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr class="hr-2" />
<table class="table">
    <thead>
        <tr class="row justify-content-center">
            <th class="col-md-1">#</th>
            <th class="col-md-2">Name</th>
            <th class="col-md-2">Price</th>
            <th class="col-md-2">Category</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Count(); i++)
        {
            <tr class="row justify-content-center">
                <th class="col-md-1">@(i + 1)</th>
                <td class="col-md-2">@Model[i].Name</td>
                <td class="col-md-2">@Model[i].Price</td>
                <td class="col-md-2">@Model[i].Category</td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a class="btn btn-primary ms-1" asp-controller="Items" asp-action="Create">Create</a>
</div>

Auto Mapping Objects/FastFood.Core/Views/Items/Create.cshtml
@model IList<FastFood.Web.ViewModels.Items.CreateItemViewModel>

@{
    ViewData["Title"] = "Create Item";
}
<h1 class="text-center">Create Item</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Items" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" placeholder="Name..." name="name">
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input type="number" step="0.01" min="0.01" class="form-control" id="price" placeholder="Price..." name="price">
    </div>
    <div class="form-group">
        <label for="category">Category</label>
        <select id="category" class="form-control" name="CategoryId">
            @foreach (var item in Model)
            {
                    <option value="@item.CategoryId">@item.CategoryName</option>
            }
        </select>
    </div>
    <hr class="bg-secondary half-width" />
     <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary me-1">Create</button>
        <a class="btn btn-primary ms-1" asp-controller="Items" asp-action="All">View All</a>
    </div>
</form>

Auto Mapping Objects/FastFood.Core/Views/Orders/All.cshtml
@model IList<FastFood.Web.ViewModels.Orders.OrderAllViewModel>

@{
    ViewData["Title"] = "All Orders";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr class="hr-2" />
<table class="table">
    <thead>
        <tr class="row justify-content-center">
            <th class="col-md-1">#</th>
            <th class="col-md-2">OrderId</th>
            <th class="col-md-2">Customer</th>
            <th class="col-md-2">Employee</th>
            <th class="col-md-2">DateTime</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Count(); i++)
        {
            <tr class="row justify-content-center">
                <th class="col-md-1">@(i + 1)</th>
                <td class="col-md-2">@Model[i].OrderId</td>
                <td class="col-md-2">@Model[i].Customer</td>
                <td class="col-md-2">@Model[i].Employee</td>
                <td class="col-md-2">@Model[i].DateTime</td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a class="btn btn-primary ms-1" asp-controller="Orders" asp-action="Create">Create</a>
</div>

Auto Mapping Objects/FastFood.Core/Views/Orders/Create.cshtml
@model FastFood.Web.ViewModels.Orders.CreateOrderViewModel

@{
    ViewData["Title"] = "Create Order";
}
<h1 class="text-center">Create Order</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Orders" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Customer</label>
        <input type="text" class="form-control" id="customer" placeholder="Customer..." name="customer">
    </div>
    <div class="form-group">
        <label for="employee">Employee Id</label>
        <select id="employee" class="form-control" name="EmployeeId">
            @foreach (var employee in Model.Employees)
            {
                <option value="@employee">@employee</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="item">Item Id</label>
        <select id="item" class="form-control" name="ItemId">
            @foreach (var item in Model.Items)
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <input type="number" step="1" min="11" class="form-control" id="quantity" placeholder="Quantity..." name="quantity">
    </div>
    <hr class="bg-secondary half-width" />
	<div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary me-1">Create</button>
        <a class="btn btn-primary ms-1" asp-controller="Orders" asp-action="All">View All</a>
    </div>
</form>

Auto Mapping Objects/FastFood.Core/Views/Positions/All.cshtml
@model IList<FastFood.Web.ViewModels.Positions.PositionsAllViewModel>

@{
    ViewData["Title"] = "All Positions";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr class="hr-2" />
<table class="table">
    <thead>
        <tr class="row justify-content-center">
            <th class="col-md-1">#</th>
            <th class="col-md-2">Position</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Count(); i++)
        {
            <tr class="row justify-content-center">
                <th class="col-md-1">@(i + 1)</th>
                <td class="col-md-2">@Model[i].Name</td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a class="btn btn-primary ms-1" asp-controller="Positions" asp-action="Create">Create</a>
</div>

Auto Mapping Objects/FastFood.Core/Views/Positions/Create.cshtml
@{
    ViewData["Title"] = "Create Position";
}
<h1 class="text-center">Create Position</h1>
<hr class="bg-secondary half-width" />
<form class="mx-auto half-width" asp-controller="Positions" asp-action="Create" method="post">
    <div class="form-group">
        <label for="positionName">Position Name</label>
        <input type="text" class="form-control" id="positionName" placeholder="Position Name..." name="positionName">
    </div>
    <hr class="bg-secondary half-width" />
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary me-1">Create</button>
        <a class="btn btn-primary ms-1" asp-controller="Positions" asp-action="All">View All</a>
    </div>
</form>

Auto Mapping Objects/FastFood.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FastFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FastFood.Core.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FastFood</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="All">Position</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Register">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Create">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Create">Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Create">Order</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <partial name="_CookieConsentPartial" />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - FastFood
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>